# v2 syntax
version: '2'
# Named volumes
volumes:
  # MySQL Data
  scwpanel-mysql-data:
    driver: local
  # Redis Data
  scwpanel-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: scwpanel-mysql
    volumes:
      - scwpanel-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=scwpanel
      - MYSQL_DATABASE=scwpanel
      - MYSQL_USER=scwpanel
      - MYSQL_PASSWORD=scwpanel
  # Redis
  cache:
    image: redis:4.0
    container_name: scwpanel-redis
    command: --appendonly yes
    volumes:
      - scwpanel-redis-data:/data
    ports:
      - "6379:6379"
  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: scwpanel-app
    volumes:
      - .:/var/www/app-scwpanel
    ports:
      - "80:8080"
    links:
      - mysql
      - cache